config/routes.rb
Prototype::Application.routes.draw do

  resources :dispatches

  devise_for :users

  namespace :user do
    root :to => 'pcrs#index'
  end

  resources :houses do
    resources :users
    resources :pcrs
    get 'add_user', :on => :member
    get 'remove_user', :on => :member
  end

  resources :pcrs

  get "pages/home"

  root :to => 'pages#home'

end

app/models/dispatch.rb
class Dispatch < ActiveRecord::Base
end

app/models/house.rb
class House < ActiveRecord::Base
  belongs_to :owner, :class_name => 'User'
  has_many :users
  has_many :pcrs
end

app/models/pcr.rb
class Pcr < ActiveRecord::Base
  belongs_to :house
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable, REMOVED :confirmable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :house

  has_one :owned_house, :class_name => 'House', :foreign_key => :owner_id

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :owned_house_attributes

  accepts_nested_attributes_for :owned_house

  after_initialize :build_owned_house_if_missing

  after_create :ensure_user_belongs_to_owned_house
  
  protected
  def build_owned_house_if_missing
    if owned_house.nil?
      self.build_owned_house
    end
  end

  def ensure_user_belongs_to_owned_house
    if !owned_house.nil?
      self.house = owned_house
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include HousesHelper
end

app/controllers/dispatches_controller.rb
class DispatchesController < ApplicationController
  # GET /dispatches
  # GET /dispatches.xml
  def index
    @dispatches = Dispatch.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dispatches }
    end
  end

  # GET /dispatches/1
  # GET /dispatches/1.xml
  def show
    @dispatch = Dispatch.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dispatch }
    end
  end

  # GET /dispatches/new
  # GET /dispatches/new.xml
  def new
    @dispatch = Dispatch.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dispatch }
    end
  end

  # GET /dispatches/1/edit
  def edit
    @dispatch = Dispatch.find(params[:id])
  end

  # POST /dispatches
  # POST /dispatches.xml
  def create
    @dispatch = Dispatch.new(params[:dispatch])

    respond_to do |format|
      if @dispatch.save
        format.html { redirect_to(@dispatch, :notice => 'Dispatch was successfully created.') }
        format.xml  { render :xml => @dispatch, :status => :created, :location => @dispatch }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dispatch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dispatches/1
  # PUT /dispatches/1.xml
  def update
    @dispatch = Dispatch.find(params[:id])

    respond_to do |format|
      if @dispatch.update_attributes(params[:dispatch])
        format.html { redirect_to(@dispatch, :notice => 'Dispatch was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dispatch.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dispatches/1
  # DELETE /dispatches/1.xml
  def destroy
    @dispatch = Dispatch.find(params[:id])
    @dispatch.destroy

    respond_to do |format|
      format.html { redirect_to(dispatches_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  # GET /houses
  # GET /houses.xml
  def index
    @houses = House.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @houses }
    end
  end

  # GET /houses/1
  # GET /houses/1.xml
  def show
    @house = House.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @house }
    end
  end

  # GET /houses/new
  # GET /houses/new.xml
  def new
    @house = House.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @house }
    end
  end

  # GET /houses/1/edit
  def edit
    @house = House.find(params[:id])
  end

  # POST /houses
  # POST /houses.xml
  def create
    @house = House.new(params[:house])

    respond_to do |format|
      if @house.save
        format.html { redirect_to(@house, :notice => 'House was successfully created.') }
        format.xml  { render :xml => @house, :status => :created, :location => @house }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @house.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /houses/1
  # PUT /houses/1.xml
  def update
    @house = House.find(params[:id])

    respond_to do |format|
      if @house.update_attributes(params[:house])
        format.html { redirect_to(@house, :notice => 'House was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @house.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1
  # DELETE /houses/1.xml
  def destroy
    @house = House.find(params[:id])
    @house.destroy

    respond_to do |format|
      format.html { redirect_to(houses_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/pcrs_controller.rb
class PcrsController < ApplicationController
  # GET /pcrs
  # GET /pcrs.xml
  def index
    @house = current_house
    @pcrs = @house.pcrs

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pcrs }
    end
  end

  # GET /pcrs/1
  # GET /pcrs/1.xml
  def show
    @pcr = Pcr.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pcr }
    end
  end

  # GET /pcrs/new
  # GET /pcrs/new.xml
  def new
    @pcr = current_house.pcrs.build

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pcr }
    end
  end

  # GET /pcrs/1/edit
  def edit
    @pcr = Pcr.find(params[:id])
  end

  # POST /pcrs
  # POST /pcrs.xml
  def create
    @pcr = current_house.pcrs.build(params[:pcr])

    respond_to do |format|
      if @pcr.save
        format.html { redirect_to(@pcr, :notice => 'Pcr was successfully created.') }
        format.xml  { render :xml => @pcr, :status => :created, :location => @pcr }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pcr.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pcrs/1
  # PUT /pcrs/1.xml
  def update
    @pcr = Pcr.find(params[:id])

    respond_to do |format|
      if @pcr.update_attributes(params[:pcr])
        format.html { redirect_to(@pcr, :notice => 'Pcr was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pcr.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pcrs/1
  # DELETE /pcrs/1.xml
  def destroy
    @pcr = Pcr.find(params[:id])
    @pcr.destroy

    respond_to do |format|
      format.html { redirect_to(pcrs_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dispatches_helper.rb
module DispatchesHelper
end

app/helpers/houses_helper.rb
module HousesHelper

  def current_house
    @current_house = current_user.house
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pcrs_helper.rb
module PcrsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dispatches/_form.html.erb
<%= form_for(@dispatch) do |f| %>
  <% if @dispatch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dispatch.errors.count, "error") %> prohibited this dispatch from being saved:</h2>

      <ul>
      <% @dispatch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :pcr_id %><br />
    <%= f.text_field :pcr_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dispatches/edit.html.erb
<h1>Editing dispatch</h1>

<%= render 'form' %>

<%= link_to 'Show', @dispatch %> |
<%= link_to 'Back', dispatches_path %>

app/views/dispatches/index.html.erb
<h1>Listing dispatches</h1>

<table>
  <tr>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>Pcr</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dispatches.each do |dispatch| %>
  <tr>
    <td><%= dispatch.address %></td>
    <td><%= dispatch.city %></td>
    <td><%= dispatch.state %></td>
    <td><%= dispatch.zip %></td>
    <td><%= dispatch.pcr_id %></td>
    <td><%= link_to 'Show', dispatch %></td>
    <td><%= link_to 'Edit', edit_dispatch_path(dispatch) %></td>
    <td><%= link_to 'Destroy', dispatch, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dispatch', new_dispatch_path %>

app/views/dispatches/new.html.erb
<h1>New dispatch</h1>

<%= render 'form' %>

<%= link_to 'Back', dispatches_path %>

app/views/dispatches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Address:</b>
  <%= @dispatch.address %>
</p>

<p>
  <b>City:</b>
  <%= @dispatch.city %>
</p>

<p>
  <b>State:</b>
  <%= @dispatch.state %>
</p>

<p>
  <b>Zip:</b>
  <%= @dispatch.zip %>
</p>

<p>
  <b>Pcr:</b>
  <%= @dispatch.pcr_id %>
</p>


<%= link_to 'Edit', edit_dispatch_path(@dispatch) %> |
<%= link_to 'Back', dispatches_path %>

app/views/houses/_form.html.erb
<%= form_for(@house) do |f| %>
  <% if @house.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
      <% @house.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render 'form' %>

<%= link_to 'Show', @house %> |
<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<h1>Listing houses</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @houses.each do |house| %>
  <tr>
    <td><%= house.name %></td>
    <td><%= link_to 'Show', house %></td>
    <td><%= link_to 'Edit', edit_house_path(house) %></td>
    <td><%= link_to 'Destroy', house, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New House', new_house_path %>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render 'form' %>

<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @house.name %>
</p>


<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prototype</title>
    <%= stylesheet_link_tag "jquery-ui-1.8.16.custom.css", 'custom' %>
    <%= javascript_include_tag "jquery-1.6.2.min.js", "jquery-ui-1.8.16.custom.min.js", "jquery_ujs.js", "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div class="container round">
      <section class="round">
      <% flash.each do |key, value| -%>
        <%= content_tag(:div, value, :class => "flash #{key}") %>
      <% end -%>
      <%= yield %>
      </section>
    </div>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<% if user_signed_in? -%>
  <p><%= current_user.email %> is signed in</p>
  <p><%= link_to 'Sign out', destroy_user_session_path %></p>
  <p><%= link_to 'Edit user', edit_user_registration_path %></p>
<% else -%>
  <p><%= link_to 'Sign in', new_user_session_path %></p>
  <p><%= link_to 'Sign up', new_user_registration_path %></p>
<% end -%>

app/views/pcrs/_form.html.erb
<%= form_for(@pcr) do |f| %>
  <% if @pcr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pcr.errors.count, "error") %> prohibited this pcr from being saved:</h2>

      <ul>
      <% @pcr.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pcr_number %><br />
    <%= f.text_field :pcr_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pcrs/edit.html.erb
<h1>Editing pcr</h1>

<div class="wrapper">
  <div id="pcr_accordion">
    <h3><%= link_to "Dispatch", "#dispatch" %></h3>
    <div>
      <p>Times</p>
      <p>Address</p>
      <p>Dispatch Info</p>
    </div>
    <h3><%= link_to "Physical Exam", "#physical_exam" %></h3>
    <div>
      <p>Patient Protective Devices Used</p>
      <p>Pre-Existing Conditions</p>
      <p>GCS</p>
    </div>
    <h3><%= link_to "Patient Info", "@patient_info" %></h3>
    <div>
      <p>Name</p>
      <p>Home Address</p>
      <p>Hx</p>
      <p>Meds & Allergies</p>
    </div>
  </div>

  <div class="pcr_content">
    <p><%= render 'form' %></p>
    <%= link_to 'Show', @pcr %> |
    <%= link_to 'Back', pcrs_path %>

  </div>

</div>

app/views/pcrs/index.html.erb
<h1>Listing pcrs for House:  <%= @house.name %></h1>

<table>
  <tr>
    <th>Pcr number</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pcrs.each do |pcr| %>
  <tr>
    <td><%= pcr.pcr_number %></td>
    <td><%= link_to 'Show', pcr %></td>
    <td><%= link_to 'Edit', edit_pcr_path(pcr) %></td>
    <td><%= link_to 'Destroy', pcr, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pcr', new_pcr_path %>

app/views/pcrs/new.html.erb
<h1>New pcr</h1>

<%= render 'form' %>

<%= link_to 'Back', pcrs_path %>

app/views/pcrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pcr number:</b>
  <%= @pcr.pcr_number %>
</p>


<%= link_to 'Edit', edit_pcr_path(@pcr) %> |
<%= link_to 'Back', pcrs_path %>